// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Data.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Models.Arvore", b =>
                {
                    b.Property<int>("IdArvore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("Varchar(100)");

                    b.Property<int>("EspecieId")
                        .HasColumnType("int");

                    b.Property<int>("GrupoArvoresId")
                        .HasColumnType("int");

                    b.Property<int>("Idade")
                        .HasColumnType("Int");

                    b.HasKey("IdArvore");

                    b.HasIndex("EspecieId");

                    b.HasIndex("GrupoArvoresId");

                    b.ToTable("Arvores");
                });

            modelBuilder.Entity("Models.Colheita", b =>
                {
                    b.Property<int>("IdColheita")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("ArvoreId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataColheita")
                        .HasColumnType("Date");

                    b.Property<string>("Informações")
                        .IsRequired()
                        .HasColumnType("Varchar(100)");

                    b.Property<decimal>("PesoBruto")
                        .HasColumnType("Money");

                    b.HasKey("IdColheita");

                    b.HasIndex("ArvoreId");

                    b.ToTable("Colheitas");
                });

            modelBuilder.Entity("Models.Especie", b =>
                {
                    b.Property<int>("IdEspecie")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("Varchar(100)");

                    b.HasKey("IdEspecie");

                    b.ToTable("Especies");
                });

            modelBuilder.Entity("Models.GrupoArvores", b =>
                {
                    b.Property<int>("IdGrupoArvores")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("Varchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("Varchar(100)");

                    b.HasKey("IdGrupoArvores");

                    b.ToTable("GrupoArvores");
                });

            modelBuilder.Entity("Models.Arvore", b =>
                {
                    b.HasOne("Models.Especie", "Especie")
                        .WithMany()
                        .HasForeignKey("EspecieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.GrupoArvores", "GrupoArvores")
                        .WithMany()
                        .HasForeignKey("GrupoArvoresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Especie");

                    b.Navigation("GrupoArvores");
                });

            modelBuilder.Entity("Models.Colheita", b =>
                {
                    b.HasOne("Models.Arvore", "Arvores")
                        .WithMany()
                        .HasForeignKey("ArvoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Arvores");
                });
#pragma warning restore 612, 618
        }
    }
}
